import { WorkoutProgram } from '../types/program';

export const PROGRAM_TEMPLATES: WorkoutProgram[] = [
  {
    id: 'full_body_3x',
    nameVi: 'Toàn thân 3 buổi/tuần',
    descriptionVi: 'Lý tưởng cho người mới. Tập toàn bộ cơ thể mỗi buổi, nghỉ xen kẽ.',
    emoji: '🏋️',
    daysPerWeek: 3,
    difficulty: 'beginner',
    focus: 'strength',
    estimatedMinutes: 45,
    days: [
      {
        id: 'fb3_a',
        order: 1,
        nameVi: 'Buổi A',
        focusVi: 'Toàn thân · Sức mạnh cơ bản',
        emoji: '💪',
        exercises: [
          { presetId: 'squat',         nameVi: 'Squat',         sets: 3, reps: 15, unit: 'reps' },
          { presetId: 'pushup',        nameVi: 'Hít đất',       sets: 3, reps: 20, unit: 'reps' },
          { presetId: 'lunge',         nameVi: 'Lunge',         sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'plank',         nameVi: 'Plank',         sets: 3, durationSeconds: 45, unit: 'seconds' },
        ],
      },
      {
        id: 'fb3_b',
        order: 2,
        nameVi: 'Buổi B',
        focusVi: 'Toàn thân · Cardio Mix',
        emoji: '🔥',
        exercises: [
          { presetId: 'burpee',        nameVi: 'Burpee',        sets: 3, reps: 10, unit: 'reps' },
          { presetId: 'pullup',        nameVi: 'Kéo xà',        sets: 3, reps: 8,  unit: 'reps' },
          { presetId: 'jumping_jacks', nameVi: 'Bật nhảy',      sets: 3, reps: 40, unit: 'reps' },
          { presetId: 'plank',         nameVi: 'Plank',         sets: 2, durationSeconds: 60, unit: 'seconds' },
        ],
      },
      {
        id: 'fb3_c',
        order: 3,
        nameVi: 'Buổi C',
        focusVi: 'Toàn thân · Phục hồi + Dẻo dai',
        emoji: '🧘',
        exercises: [
          { presetId: 'squat',         nameVi: 'Squat',         sets: 4, reps: 12,  unit: 'reps' },
          { presetId: 'dip',           nameVi: 'Chống đẩy ghế', sets: 3, reps: 12,  unit: 'reps' },
          { presetId: 'stretching',    nameVi: 'Giãn cơ',       sets: 1, durationSeconds: 600, unit: 'seconds' },
          { presetId: 'walking',       nameVi: 'Đi bộ',         sets: 1, durationSeconds: 1200, unit: 'seconds' },
        ],
      },
    ],
  },

  {
    id: 'push_pull_legs',
    nameVi: 'Push · Pull · Legs',
    descriptionVi: 'Chương trình PPL kinh điển. Chia nhóm cơ tối ưu, 6 buổi/tuần.',
    emoji: '💪',
    daysPerWeek: 6,
    difficulty: 'intermediate',
    focus: 'strength',
    estimatedMinutes: 60,
    days: [
      {
        id: 'ppl_push1',
        order: 1,
        nameVi: 'Ngày Đẩy A',
        focusVi: 'Ngực · Vai · Tay trước',
        emoji: '🫸',
        exercises: [
          { presetId: 'pushup', nameVi: 'Hít đất',       sets: 4, reps: 25, unit: 'reps' },
          { presetId: 'dip',    nameVi: 'Chống đẩy ghế', sets: 3, reps: 15, unit: 'reps' },
          { presetId: 'plank',  nameVi: 'Plank',         sets: 3, durationSeconds: 60, unit: 'seconds' },
        ],
      },
      {
        id: 'ppl_pull1',
        order: 2,
        nameVi: 'Ngày Kéo A',
        focusVi: 'Lưng · Vai sau · Tay sau',
        emoji: '🤸',
        exercises: [
          { presetId: 'pullup', nameVi: 'Kéo xà', sets: 4, reps: 10, unit: 'reps' },
          { presetId: 'plank',  nameVi: 'Plank',  sets: 3, durationSeconds: 45, unit: 'seconds' },
        ],
      },
      {
        id: 'ppl_legs1',
        order: 3,
        nameVi: 'Ngày Chân A',
        focusVi: 'Đùi · Mông · Bắp chân',
        emoji: '🦵',
        exercises: [
          { presetId: 'squat',         nameVi: 'Squat',    sets: 4, reps: 20, unit: 'reps' },
          { presetId: 'lunge',         nameVi: 'Lunge',    sets: 3, reps: 15, unit: 'reps' },
          { presetId: 'jumping_jacks', nameVi: 'Bật nhảy', sets: 2, reps: 50, unit: 'reps' },
        ],
      },
      {
        id: 'ppl_push2',
        order: 4,
        nameVi: 'Ngày Đẩy B',
        focusVi: 'Ngực · Vai · Tay trước (tăng tải)',
        emoji: '🫸',
        exercises: [
          { presetId: 'pushup', nameVi: 'Hít đất',       sets: 5, reps: 20, unit: 'reps' },
          { presetId: 'dip',    nameVi: 'Chống đẩy ghế', sets: 4, reps: 12, unit: 'reps' },
          { presetId: 'burpee', nameVi: 'Burpee',        sets: 3, reps: 10, unit: 'reps' },
        ],
      },
      {
        id: 'ppl_pull2',
        order: 5,
        nameVi: 'Ngày Kéo B',
        focusVi: 'Lưng · Bắp tay (tăng tải)',
        emoji: '🤸',
        exercises: [
          { presetId: 'pullup', nameVi: 'Kéo xà', sets: 5, reps: 8, unit: 'reps' },
          { presetId: 'plank',  nameVi: 'Plank',  sets: 4, durationSeconds: 60, unit: 'seconds' },
        ],
      },
      {
        id: 'ppl_legs2',
        order: 6,
        nameVi: 'Ngày Chân B',
        focusVi: 'Sức mạnh đùi · Mông (tăng tải)',
        emoji: '🦵',
        exercises: [
          { presetId: 'squat',     nameVi: 'Squat',    sets: 5, reps: 15, unit: 'reps' },
          { presetId: 'lunge',     nameVi: 'Lunge',    sets: 4, reps: 12, unit: 'reps' },
          { presetId: 'jump_rope', nameVi: 'Nhảy dây', sets: 1, durationSeconds: 600, unit: 'seconds' },
        ],
      },
    ],
  },

  {
    id: 'upper_lower',
    nameVi: 'Upper · Lower Split',
    descriptionVi: 'Tập thân trên và thân dưới xen kẽ. Cân bằng tối ưu, 4 buổi/tuần.',
    emoji: '⚡',
    daysPerWeek: 4,
    difficulty: 'intermediate',
    focus: 'strength',
    estimatedMinutes: 55,
    days: [
      {
        id: 'ul_upper_a',
        order: 1,
        nameVi: 'Thân Trên A',
        focusVi: 'Ngực · Lưng · Vai',
        emoji: '💪',
        exercises: [
          { presetId: 'pushup', nameVi: 'Hít đất', sets: 4, reps: 20, unit: 'reps' },
          { presetId: 'pullup', nameVi: 'Kéo xà',  sets: 3, reps: 10, unit: 'reps' },
          { presetId: 'dip',    nameVi: 'Chống đẩy ghế', sets: 3, reps: 12, unit: 'reps' },
        ],
      },
      {
        id: 'ul_lower_a',
        order: 2,
        nameVi: 'Thân Dưới A',
        focusVi: 'Đùi · Mông · Bắp chân',
        emoji: '🦵',
        exercises: [
          { presetId: 'squat',     nameVi: 'Squat',    sets: 4, reps: 18, unit: 'reps' },
          { presetId: 'lunge',     nameVi: 'Lunge',    sets: 3, reps: 15, unit: 'reps' },
          { presetId: 'jump_rope', nameVi: 'Nhảy dây', sets: 1, durationSeconds: 300, unit: 'seconds' },
        ],
      },
      {
        id: 'ul_upper_b',
        order: 3,
        nameVi: 'Thân Trên B',
        focusVi: 'Ngực · Bắp tay · Core',
        emoji: '💪',
        exercises: [
          { presetId: 'pushup', nameVi: 'Hít đất', sets: 5, reps: 15, unit: 'reps' },
          { presetId: 'pullup', nameVi: 'Kéo xà',  sets: 4, reps: 8,  unit: 'reps' },
          { presetId: 'plank',  nameVi: 'Plank',   sets: 4, durationSeconds: 60, unit: 'seconds' },
        ],
      },
      {
        id: 'ul_lower_b',
        order: 4,
        nameVi: 'Thân Dưới B',
        focusVi: 'Sức mạnh đùi · Cardio',
        emoji: '🦵',
        exercises: [
          { presetId: 'squat',         nameVi: 'Squat',    sets: 5, reps: 15, unit: 'reps' },
          { presetId: 'burpee',        nameVi: 'Burpee',   sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'jumping_jacks', nameVi: 'Bật nhảy', sets: 3, reps: 50, unit: 'reps' },
        ],
      },
    ],
  },

  {
    id: 'cardio_blast',
    nameVi: 'Cardio Blast',
    descriptionVi: 'Cardio cường độ cao xen kẽ active recovery. Đốt mỡ hiệu quả.',
    emoji: '🏃',
    daysPerWeek: 5,
    difficulty: 'intermediate',
    focus: 'cardio',
    estimatedMinutes: 35,
    days: [
      {
        id: 'cb_1',
        order: 1,
        nameVi: 'HIIT A',
        focusVi: 'Cường độ cao · Đốt mỡ',
        emoji: '🔥',
        exercises: [
          { presetId: 'burpee',        nameVi: 'Burpee',    sets: 4, reps: 15, unit: 'reps' },
          { presetId: 'jumping_jacks', nameVi: 'Bật nhảy',  sets: 4, reps: 50, unit: 'reps' },
          { presetId: 'jump_rope',     nameVi: 'Nhảy dây',  sets: 1, durationSeconds: 600, unit: 'seconds' },
        ],
      },
      {
        id: 'cb_2',
        order: 2,
        nameVi: 'Steady State',
        focusVi: 'Bền bỉ · Aerobic',
        emoji: '🚴',
        exercises: [
          { presetId: 'cycling',    nameVi: 'Đạp xe',  sets: 1, durationSeconds: 1800, unit: 'seconds' },
          { presetId: 'stretching', nameVi: 'Giãn cơ', sets: 1, durationSeconds: 600,  unit: 'seconds' },
        ],
      },
      {
        id: 'cb_3',
        order: 3,
        nameVi: 'HIIT B',
        focusVi: 'Tăng tốc · Endurance',
        emoji: '⚡',
        exercises: [
          { presetId: 'running',       nameVi: 'Chạy bộ',  sets: 1, durationSeconds: 1200, unit: 'seconds' },
          { presetId: 'jumping_jacks', nameVi: 'Bật nhảy', sets: 3, reps: 60, unit: 'reps' },
        ],
      },
      {
        id: 'cb_4',
        order: 4,
        nameVi: 'Active Recovery',
        focusVi: 'Nhẹ nhàng · Phục hồi',
        emoji: '🌿',
        exercises: [
          { presetId: 'walking', nameVi: 'Đi bộ', sets: 1, durationSeconds: 1800, unit: 'seconds' },
          { presetId: 'yoga',    nameVi: 'Yoga',  sets: 1, durationSeconds: 900,  unit: 'seconds' },
        ],
      },
      {
        id: 'cb_5',
        order: 5,
        nameVi: 'Peak Day',
        focusVi: 'Đỉnh cao tuần',
        emoji: '🏆',
        exercises: [
          { presetId: 'burpee',    nameVi: 'Burpee',    sets: 5, reps: 12, unit: 'reps' },
          { presetId: 'jump_rope', nameVi: 'Nhảy dây',  sets: 2, durationSeconds: 600, unit: 'seconds' },
          { presetId: 'running',   nameVi: 'Chạy bộ',   sets: 1, durationSeconds: 600, unit: 'seconds' },
        ],
      },
    ],
  },

  {
    id: 'mobility_flow',
    nameVi: 'Mobility & Flow',
    descriptionVi: 'Tăng độ dẻo dai và linh hoạt. Phù hợp tập sau workout nặng.',
    emoji: '🧘',
    daysPerWeek: 3,
    difficulty: 'beginner',
    focus: 'mobility',
    estimatedMinutes: 30,
    days: [
      {
        id: 'mf_1',
        order: 1,
        nameVi: 'Yoga Flow',
        focusVi: 'Toàn thân · Thư giãn',
        emoji: '🌅',
        exercises: [
          { presetId: 'yoga',       nameVi: 'Yoga',    sets: 1, durationSeconds: 1200, unit: 'seconds' },
          { presetId: 'stretching', nameVi: 'Giãn cơ', sets: 1, durationSeconds: 600,  unit: 'seconds' },
        ],
      },
      {
        id: 'mf_2',
        order: 2,
        nameVi: 'Deep Stretch',
        focusVi: 'Linh hoạt · Phục hồi',
        emoji: '🤸',
        exercises: [
          { presetId: 'stretching',    nameVi: 'Giãn cơ',    sets: 1, durationSeconds: 900,  unit: 'seconds' },
          { presetId: 'foam_rolling',  nameVi: 'Lăn cơ',     sets: 1, durationSeconds: 600,  unit: 'seconds' },
          { presetId: 'walking',       nameVi: 'Đi bộ nhẹ',  sets: 1, durationSeconds: 1200, unit: 'seconds' },
        ],
      },
      {
        id: 'mf_3',
        order: 3,
        nameVi: 'Strength Mobility',
        focusVi: 'Sức mạnh + Dẻo dai',
        emoji: '🌿',
        exercises: [
          { presetId: 'plank',         nameVi: 'Plank',    sets: 3, durationSeconds: 45, unit: 'seconds' },
          { presetId: 'yoga',          nameVi: 'Yoga',     sets: 1, durationSeconds: 900, unit: 'seconds' },
          { presetId: 'foam_rolling',  nameVi: 'Lăn cơ',  sets: 1, durationSeconds: 300, unit: 'seconds' },
        ],
      },
    ],
  },

  {
    id: 'dumbbell_home_3x',
    nameVi: 'Tạ đơn Toàn thân 3x/tuần',
    descriptionVi: 'Tập tạ đơn tại nhà toàn thân. Chỉ cần 1 đôi tạ, lý tưởng cho người mới.',
    emoji: '🏋️',
    daysPerWeek: 3,
    difficulty: 'beginner',
    focus: 'strength',
    estimatedMinutes: 40,
    days: [
      {
        id: 'db3_a',
        order: 1,
        nameVi: 'Buổi A — Ngực & Tay',
        focusVi: 'Đẩy ngực · Tay trước · Tay sau',
        emoji: '💪',
        exercises: [
          { presetId: 'db_chest_press',    nameVi: 'Đẩy Ngực Tạ',     sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_bicep_curl',     nameVi: 'Curl Tay Trước',   sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_tricep_ext',     nameVi: 'Tay Sau Tạ',       sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_shoulder_press', nameVi: 'Đẩy Vai Tạ',       sets: 3, reps: 10, unit: 'reps' },
        ],
      },
      {
        id: 'db3_b',
        order: 2,
        nameVi: 'Buổi B — Lưng & Vai',
        focusVi: 'Kéo lưng · Vai · Hammer',
        emoji: '🔥',
        exercises: [
          { presetId: 'db_bent_row',      nameVi: 'Kéo Lưng Tạ',      sets: 3, reps: 10, unit: 'reps' },
          { presetId: 'db_lateral_raise', nameVi: 'Nâng Ngang Vai',    sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_front_raise',   nameVi: 'Nâng Trước Vai',    sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_hammer_curl',   nameVi: 'Hammer Curl',       sets: 3, reps: 12, unit: 'reps' },
        ],
      },
      {
        id: 'db3_c',
        order: 3,
        nameVi: 'Buổi C — Chân & Core',
        focusVi: 'Đùi · Mông · Core',
        emoji: '🦵',
        exercises: [
          { presetId: 'db_goblet_squat', nameVi: 'Squat Tạ Goblet',     sets: 4, reps: 15, unit: 'reps' },
          { presetId: 'db_rdl',          nameVi: 'Romanian Deadlift Tạ', sets: 3, reps: 10, unit: 'reps' },
          { presetId: 'plank',           nameVi: 'Plank',                sets: 3, durationSeconds: 45, unit: 'seconds' },
          { presetId: 'lunge',           nameVi: 'Lunge',                sets: 3, reps: 12, unit: 'reps' },
        ],
      },
    ],
  },

  {
    id: 'dumbbell_ppl',
    nameVi: 'Tạ đơn Push · Pull · Legs',
    descriptionVi: 'PPL tạ đơn tại nhà. Chia nhóm cơ rõ ràng, tăng tải dần mỗi tuần.',
    emoji: '💪',
    daysPerWeek: 3,
    difficulty: 'intermediate',
    focus: 'strength',
    estimatedMinutes: 50,
    days: [
      {
        id: 'dbppl_push',
        order: 1,
        nameVi: 'Push — Ngực · Vai · Tay sau',
        focusVi: 'Ngực · Vai · Tricep',
        emoji: '🫸',
        exercises: [
          { presetId: 'db_chest_press',    nameVi: 'Đẩy Ngực Tạ',  sets: 4, reps: 12, unit: 'reps' },
          { presetId: 'db_shoulder_press', nameVi: 'Đẩy Vai Tạ',   sets: 3, reps: 10, unit: 'reps' },
          { presetId: 'db_lateral_raise',  nameVi: 'Nâng Ngang Vai', sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_tricep_ext',     nameVi: 'Tay Sau Tạ',    sets: 3, reps: 12, unit: 'reps' },
        ],
      },
      {
        id: 'dbppl_pull',
        order: 2,
        nameVi: 'Pull — Lưng · Tay trước',
        focusVi: 'Lưng · Bicep · Vai sau',
        emoji: '🤸',
        exercises: [
          { presetId: 'db_bent_row',     nameVi: 'Kéo Lưng Tạ',   sets: 4, reps: 10, unit: 'reps' },
          { presetId: 'db_bicep_curl',   nameVi: 'Curl Tay Trước', sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_hammer_curl',  nameVi: 'Hammer Curl',    sets: 3, reps: 12, unit: 'reps' },
          { presetId: 'db_front_raise',  nameVi: 'Nâng Trước Vai', sets: 3, reps: 12, unit: 'reps' },
        ],
      },
      {
        id: 'dbppl_legs',
        order: 3,
        nameVi: 'Legs — Chân · Mông',
        focusVi: 'Đùi · Mông · Core',
        emoji: '🦵',
        exercises: [
          { presetId: 'db_goblet_squat', nameVi: 'Squat Tạ Goblet',     sets: 4, reps: 15, unit: 'reps' },
          { presetId: 'db_rdl',          nameVi: 'Romanian Deadlift Tạ', sets: 4, reps: 10, unit: 'reps' },
          { presetId: 'lunge',           nameVi: 'Lunge',                sets: 3, reps: 14, unit: 'reps' },
          { presetId: 'plank',           nameVi: 'Plank',                sets: 3, durationSeconds: 60, unit: 'seconds' },
        ],
      },
    ],
  },

];

export const DIFFICULTY_LABELS: Record<string, string> = {
  beginner:     'Người mới',
  intermediate: 'Trung cấp',
  advanced:     'Nâng cao',
};

export const FOCUS_LABELS: Record<string, string> = {
  strength: 'Sức mạnh',
  cardio:   'Cardio',
  mixed:    'Kết hợp',
  mobility: 'Dẻo dai',
};
